name: GEOMETRIA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42798
title: GEOMETRIA - architecture and geometry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e7367'
    - '#4f4238'
    - '#c2bbb7'
    - '#231408'
    - '#ffffff'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
